### ISSUE TITLE
build error  (0.10.29 | darwin | x64)

### ISSUE THREAD

**Issue by TilmanGriesel** [dturing/node-gstreamer-superficial#1]
Hi Daniel, nice work!

But I get a strange  build error. I can't figure out why v8::ArrayBuffer should be a problem, but I'm not a Node / C++ expert.

-----------------------------------------------------------------------------------------------

node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.29 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/gstreamer-superficial/gstreamer.o
../gstreamer.cc:12:47: error: no member named 'ArrayBuffer' in namespace 'v8'
class MallocArrayBufferAllocator : public v8::ArrayBuffer::Allocator {
                                          ~~~~^
../gstreamer.cc:12:60: error: expected class name
class MallocArrayBufferAllocator : public v8::ArrayBuffer::Allocator {
                                                           ^
../gstreamer.cc:586:4: error: no member named 'SetArrayBufferAllocator' in 'v8::V8'; did you mean 'MallocArrayBufferAllocator'?
        v8::V8::SetArrayBufferAllocator(new MallocArrayBufferAllocator());
        ^~~~~~~~
../gstreamer.cc:12:7: note: 'MallocArrayBufferAllocator' declared here
class MallocArrayBufferAllocator : public v8::ArrayBuffer::Allocator {
      ^
3 errors generated.
make: *** [Release/obj.target/gstreamer-superficial/gstreamer.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

-----------------------------------------------------------------------------------------------

**Comment by c-o-m-m-a-n-d-e-r** [comment]
have this error on Raspberry pi 2 with jessie ... any change get this running?

**Comment by dturing** [comment]
i have merged some work and updated for nan2; without having looked into your problem (time, life and such, sorry)- could you give it another try now please?

**Comment by dturing** [comment]
assuming it builds now, closing issue
