### ISSUE TITLE
Feature request: Pushing data to GStreamer

### ISSUE THREAD

**Issue by tvandergeer** [dturing/node-gstreamer-superficial#10]
Do you think it will be possible to push data from NodeJS into Gstreamer? Within Gstreamer there's an element named "[appsrc](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-appsrc.html)" which allows applications to push data (buffers) into GStreamer. I was thinking something along the line of:
```
pipeline.push([buffer]);
```

**Comment by dturing** [comment]
Tom,

that's surely possible; node-gstreamer-superficial already does the opposite with appsink. It wouldnt be a pipeline function, but rather on the appsrc element.

However, this is a unpaid, voluntary, opensource project. We're not really accepting feature requests ;) I'd be happy to merge a PR implementing it.

**Comment by tvandergeer** [comment]
Ha! That sounds like a nice challenge to brush up my C++ skills...

**Comment by Zubnix** [comment]
Did this get any love? I'm looking for the same thing...

**Comment by tvandergeer** [comment]
I found other challenges, so I didn't get around to finish it.

**Comment by Zubnix** [comment]
https://github.com/udevbe/node-gstreamer-superficial/commit/3808dac17d1bfebef3079a7802e3b6d498b54831

This is my first try @ c++ & native node so early comments welcome :)
