### ISSUE TITLE
One problem about 'get_pipeline_get_latyecy'

### ISSUE THREAD

**Issue by aokihu** [dturing/node-gstreamer-superficial#11]
`../Pipeline.cpp: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE Pipeline::GetLatency(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../Pipeline.cpp:215:70: error: ‘gst_pipeline_get_latency’ was not declared in this scope
  double secs = NANOS_TO_DOUBLE(gst_pipeline_get_latency(obj->pipeline));
                                                                      ^
../Pipeline.cpp:12:41: note: in definition of macro ‘NANOS_TO_DOUBLE’
 #define NANOS_TO_DOUBLE(nanos)(((double)nanos)/1000000000)
                                         ^
../Pipeline.cpp: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Pipeline::SetLatency(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../Pipeline.cpp:221:80: error: ‘gst_pipeline_set_latency’ was not declared in this scope
   gst_pipeline_set_latency(obj->pipeline, DOUBLE_TO_NANOS(value->NumberValue()));
                                                                                ^
gstreamer-superficial.target.mk:101: recipe for target 'Release/obj.target/gstreamer-superficial/Pipeline.o' failed`

I build on arm platform with OS ubuntu, my gstreamer include file have not 'gst_pipeline_get_latency' and 'get_pipeline_set_latency', these two method maybe not use usually, would you remove two method?

**Comment by dturing** [comment]
gst_pipeline_get_latency exists since Gstreamer 1.6, released September 2015. That seems a reasonable requirement to me...

**Comment by aokihu** [comment]
I will check my streamer version, thank your reply
