### ISSUE TITLE
runtime problem

### ISSUE THREAD

**Issue by aokihu** [dturing/node-gstreamer-superficial#13]
> module.js:598
>
>return process.dlopen(module, path._makeLong(filename));
>               ^
>
>Error: /home/aokihu/gst-test/node_modules/gstreamer-superficial/build/Release/gstreamer-superficial.node: undefined symbol: _ZN8Pipeline10GetLatencyEN2v85LocalINS0_6StringEEERKN3Nan20PropertyCallbackInfoINS0_5ValueEEE

new problem, why?

**Comment by dturing** [comment]
hard to say for sure, but this looks like it's trying to (run-time-)link to an older gstreamer library than what it linked against (where GetLatency is not implemented - likely related to your issue #11).
