### ISSUE TITLE
Is it possible to console.log whatever data comes to each element?

### ISSUE THREAD

**Issue by thehappycoder** [dturing/node-gstreamer-superficial#25]
I have this pipeline:
`dataurisrc uri="data:text/plain;base64,${sdpBase64String}"` +
    ` ! sdpdemux latency=10000 timeout=0 ! parsebin ! mp4mux ! filesink location=${outputPath}`

I wonder if I can peek at what's going on in parsebin?

**Comment by dturing** [comment]
sorry for the late reply. you can use either the "identity" element with dump=true, or if you really want the data in your node process, use tee and appsink.
