### ISSUE TITLE
node-gstreamer-superficial crashes nodejs process

### ISSUE THREAD

**Issue by thehappycoder** [dturing/node-gstreamer-superficial#26]
It looks like node-gstreamer-superficial crashes sometimes, which seems to be killing the entire nodejs process.

It may be crashing due to gstreamer bug. If yes, I am hoping that node-gstreamer-superficial can handle it gracefully without killing the entire nodejs process.

**Comment by dturing** [comment]
AFAICT, we cannot catch segfaults that happen in gstreamer elements; sorry.
