### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by FibHeap** [dturing/node-gstreamer-superficial#32]
It seems npm install fails on node 12 (12.12.0). Handle is not defined.

```
> node-gyp rebuild

make: Entering directory '/home/manuel/playground/node_modules/gstreamer-superficial/build'
  CXX(target) Release/obj.target/gstreamer-superficial/gstreamer.o
In file included from ../gstreamer.cpp:4:0:
../GLibHelpers.h:9:1: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
 Handle<Object> createBuffer(char *data, int length);
 ^~~~~~
 rand_r
../GLibHelpers.h:11:1: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
 Handle<Value> gstsample_to_v8( GstSample *sample );
 ^~~~~~
 rand_r
../GLibHelpers.h:12:1: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
 Handle<Value> gstvaluearray_to_v8( const GValue *gv );
 ^~~~~~
 rand_r
../GLibHelpers.h:13:1: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
 Handle<Value> gvalue_to_v8( const GValue *gv );
```

Is there already a workaround?

**Comment by molecular** [comment]
I second this issue (using node v13)

I doubt there's a "workaround" (less downgrading node). Code just needs to be migrated.

I tried replacing all Handle<...> with Local<...> and that got rid of the "Handle not defined" error (not sure if it is correct, though), but I'm getting more deprecation problems. There's a guide how to convert: https://github.com/bcoin-org/bcrypto/issues/7. Tried to use that, but got stuck at some point. That stuff is just over my head at this point.

@dturing can you help?

I'm offering a bounty of 1 BCH (Bitcoin Cash) to solve this and get it merged here.

**Comment by dturing** [comment]
should be fine with release 1.3.0

**Comment by molecular** [comment]
cool!

still having issues (3 similar ones like the following):

```
../GObjectWrap.cpp:36:82: error: ‘class v8::Local<v8::String>’ has no member named ‘ToLocalChecked’
   36 |  constructorLocal->SetName(String::NewFromUtf8(isolate, G_OBJECT_TYPE_NAME(obj)).ToLocalChecked());
```

this is with node v12.11.0

**Comment by dturing** [comment]
after a9f3d7cad6809c8fffacbf67627ec5714d36272b (rel 1.3.1), works (for me) with node 12.11 and 13.2

**Comment by molecular** [comment]
bounty unlocked.

@dturing give me a BCH address, please.

**Comment by dturing** [comment]
via PM, and thank you!

**Comment by molecular** [comment]
thank *you*

**Comment by dturing** [comment]
@molecular received, thanks again!
