### ISSUE TITLE
Newer versions of Node.js show `illegal hardware instructions` error

### ISSUE THREAD

**Issue by chrisspiegl** [dturing/node-gstreamer-superficial#36]
Hello, as mentioned in the other issue, I am new to Gstreamer and this package.

At first I tried installing this package on node version 12.14.1 and wonderred why it would through the 

```
[1]    18705 illegal hardware instruction  ./test.js
```

error message. Then I found that this is currently only compatible up until 12.11.

Maybe this issue can be a path to upgrading the package to be compatible with the newest LTS version v12.16?

Thanks, Chris.

**Comment by dturing** [comment]
Hey @chrisspiegl , i have just tried the npm module 1.3.1 with both nodejs lts 12.16 and nodejs 13.13, without any problem. What makes you think it's only compatible until 12.11?

**Comment by chrisspiegl** [comment]
Hello @dturing, that is interesting. Maybe it was about the operating system rather than the node version at the end. I am not sure and will not have any more time to test this further, so I am going to close this issue for now.
