### ISSUE TITLE
Example for receiving current Position

### ISSUE THREAD

**Issue by infantilo** [dturing/node-gstreamer-superficial#40]
Hi!
Thanks for your great work!

Could you PLZ give an example, of how to receive the current play position?

pipeline.query_position(gst.FORMAT_TIME)

THANKS for advice

**Comment by dturing** [comment]
Hi. i've just added queryPosition and queryDuration (version 1.6.0). They return TIME in seconds. Example: https://github.com/dturing/node-gstreamer-superficial/blob/master/examples/query.js

**Comment by infantilo** [comment]
Working like charm!
Thanks a lot for really quick help and update!!!!!!!!
