### ISSUE TITLE
Gstreamer pipeline debugging

### ISSUE THREAD

**Issue by valerymagadeeva** [dturing/node-gstreamer-superficial#43]
Is there any opportunity to debug Gstreamer pipeline using log levels and gstreamer's graph system? I mean, I used to debug the pipeline using `GST_DEBUG_DUMP_DOT_DIR` env var to generate special dot graph. Moreover, it's useful to define special debugging level to see all memory dump or just debug info logs. Are these things somehow possible with this package? Thanks in advance.

**Comment by dfischer23** [comment]
Hi @valerymagadeeva, there are no provisions in this library (yet?) For this, but have you tried setting the environment vars like you would with gst-launch?

**Comment by valerymagadeeva** [comment]
@dfischer23 thanks for the answer! Yes, I've set the env var in my package.json at 'start' script. It used to work earlier, when I just 'spawned' the gstreamer pipeline, but now it doesn't.

**Comment by dturing** [comment]
hmm. `GST_DEBUG=5 node examples/test.js` gives me the expected lots of gst debug output. can you give an example that wont work, @valerymagadeeva ?

**Comment by dturing** [comment]
closing because inactive., please reopen if more information available.
