### ISSUE TITLE
How to get stream object?

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [dturing/node-gstreamer-superficial#44]
Hi,

I want to get stream object like in the below code:

```
Stream = require('node-rtsp-stream');
            stream = new Stream({
                    streamUrl: 'rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen02.stream',
                    wsPort: 9999
            })
            console.log('[MASTER] created rtsp stream'+JSON.stringify(stream));
            master.localStream = stream;

```
Is there a way to get stream object using gstreamer-superficial?

**Comment by dturing** [comment]
The "Stream" class you mention is a construct of node-rtsp-stream/JSMpeg. It has nothing to do with gstreamer or node-gstreamer-superficial.

**Comment by HimanshuVerma18111989** [comment]
Have you even read the complete question?

**Comment by dturing** [comment]
@HimanshuVerma18111989 yes, i have read the complete question. it is not very long.

in your example, you are importing node-rtsp-stream, and create a new Stream object from it. There is no such construct in gstreamer-superficial, or gstreamer..

is your question "How do i play an RTSP stream with gstreamer-superficial"?

**Comment by dturing** [comment]
I had a short look at node-rtsp-stream. If you expect gstreamer-superficial to receive the RTSP stream and send it to a Websocket, like node-rtsp-stream does, then no- there is no way to "get stream object". AFAIK, GStreamer doesn't implement anything related to websockets. You *might* achieve the same functionality with an appsink and feeding the websocket from node.
