### ISSUE TITLE
webrtcbin usage [feature request]

### ISSUE THREAD

**Issue by ldenoue** [dturing/node-gstreamer-superficial#48]
First, thanks for creating this NodeJS bindings for GStreamer.
Lately, I've discovered the rather new webrtcbin element and wondered what we need to add to gstreamer-superficial to make it usable here.

For reference, here's a python sample code (simpler to understand) that shows interactions with this webrtcbin element:
https://gitlab.freedesktop.org/gstreamer/gst-examples/-/blob/master/webrtc/sendrecv/gst/webrtc_sendrecv.py#L129

In particular how could we modify the cpp wrapper files used by gstreamer-superficial to add these:

`GstSdp.SDPMessage.new`
`GstSdp.sdp_message_parse_buffer`
`GstWebRTC.WebRTCSessionDescription.new`
`Gst.Promise.new`

And also can we emit things to the webrtc element, like done in
https://gitlab.freedesktop.org/gstreamer/gst-examples/-/blob/master/webrtc/sendrecv/gst/webrtc_sendrecv.py#L133

I'm aware this would make it less superficial ;)

**Comment by chfritz** [comment]
@ldenoue, FYI: I had the same need and got it to work using node-gtk instead following [this C implementation](https://github.com/hissinger/gstreamer-webrtcbin-demo/blob/main/webrtc-sendrecv.c) as an example. [These examples of working with gstreamer through node-gtk](https://github.com/wotzlaff/node-gstreamer-tutorial/tree/master/src) were also very helpful in the process.
